"""
Page scoring.

Scorer's only job: decide which pages are valuable and how valuable.
Section assignment and grouping is handled by the generator.

Scores are universal — not profile-dependent.
"""

import re
from dataclasses import dataclass
from urllib.parse import urlparse

from classifier import PageClassification
from models import CrawledPage

DROP_THRESHOLD         = 0
OPTIONAL_THRESHOLD     = 5
RELAXED_DROP_THRESHOLD = -3

# Base score per page_type — universal across all site types.
# Public so the crawler can derive pre-crawl URL priority from the same table.
PAGE_TYPE_SCORES: dict[str, int] = {
    "guide":     8,
    "product":   7,
    "pricing":   6,
    "about":     5,
    "faq":       5,
    "blog_post": 4,
    "contact":   2,
}

DEFAULT_PAGE_SCORE = 1  # any page_type not in the table (e.g. "other")

_ONBOARDING_URL = re.compile(
    r"/getting.?started|/quickstart|/quick.?start|/intro(?:duction)?$"
    r"|/overview$|/tutorial|/setup$|/install(?:ation)?$|/start$",
    re.IGNORECASE,
)

_ONBOARDING_TITLE = re.compile(
    r"getting started|quickstart|introduction|overview|tutorial|setup|installation",
    re.IGNORECASE,
)

# URL path segments that signal high or low retrieval value for an LLM.
# Checked against the lowercased path — first match wins.
_URL_BOOST_PATTERNS: list[tuple[re.Pattern, int]] = [
    (re.compile(r"/getting.?started|/quickstart"),                              5),
    (re.compile(r"/authentication|/auth(?:/|$)"),                               4),
    (re.compile(r"/overview(?:/|$)|/introduction(?:/|$)|/concepts(?:/|$)"),     3),
    (re.compile(r"/api.?reference|/reference(?:/|$)"),                         -3),
    (re.compile(r"/changelog|/releases(?:/|$)|/release.notes"),                -4),
    (re.compile(r"/sdk(?:/|$)|/client.?librar"),                               -2),
    # Old-year paths (pre-2020) are likely stale content
    (re.compile(r"/20[01]\d/"),                                                 -2),
    # Versioned docs may be outdated
    (re.compile(r"/v\d+\.\d+/"),                                               -1),
]

_LINK_RE = re.compile(r'\]\(([^)#\s]+)')


# ---------------------------------------------------------------------------
# Signal dimensions
# ---------------------------------------------------------------------------

@dataclass
class PageSignals:
    """
    Decomposed quality signals for a crawled page.

    Keeping dimensions separate allows LLM scoring to override individual
    signals (e.g. uniqueness) without touching structural ones.
    """
    information_density: float    # 0.0–1.0  word count / content richness
    technical_depth: float        # 0.0–1.0  balanced code+prose; penalises code dumps
    navigational_noise: float     # 0.0–1.0  link density — higher = more nav noise (bad)
    onboarding_value: float       # 0.0–1.0  is this a good entry point for new users?
    url_boost: int                # raw delta from high/low-value URL path patterns
    template_similarity: float    # 0.0–1.0  within-page structure repetition; higher = template-like
    internal_link_authority: int  # count of other crawled pages that link here
    uniqueness: float = 0.5       # placeholder — reserved for future LLM scoring


# ---------------------------------------------------------------------------
# Output type
# ---------------------------------------------------------------------------

@dataclass
class ScoredPage:
    page: CrawledPage
    page_type: str
    score: int
    signals: PageSignals
    included: bool = False


# ---------------------------------------------------------------------------
# Scoring helpers
# ---------------------------------------------------------------------------

def _base_score(page_type: str) -> int:
    return PAGE_TYPE_SCORES.get(page_type, DEFAULT_PAGE_SCORE)


def compute_url_boost(url: str) -> int:
    """
    Return a score delta for a URL based on path patterns that signal
    high or low retrieval value. Public so crawler.py can use the same
    signal for pre-crawl prioritisation.
    """
    path = urlparse(url).path.lower()
    for pattern, delta in _URL_BOOST_PATTERNS:
        if pattern.search(path):
            return delta
    return 0


def _compute_template_similarity(content: str) -> float:
    """
    Detect template-like pages (autogenerated API references, endpoint lists)
    by looking for many short sections. No cross-page comparison needed.
    """
    lines = content.splitlines()
    heading_count = sum(1 for l in lines if l.startswith("## ") or l.startswith("### "))
    if heading_count == 0:
        return 0.0
    words_per_heading = len(content.split()) / heading_count
    if heading_count > 20 and words_per_heading < 50:
        return 0.9   # many tiny sections = highly template-like
    if heading_count > 10 and words_per_heading < 80:
        return 0.6
    return 0.1


def _compute_incoming_links(pages: list[CrawledPage]) -> dict[str, int]:
    """
    Count how many other crawled pages link to each page.
    Uses path-based matching so relative and absolute links both resolve.
    Important pages naturally accumulate links — cheap approximation of PageRank.
    """
    path_to_url = {urlparse(p.url).path.rstrip("/") or "/": p.url for p in pages}
    counts: dict[str, int] = {p.url: 0 for p in pages}

    for page in pages:
        seen: set[str] = set()
        for match in _LINK_RE.finditer(page.content):
            href = match.group(1)
            try:
                path = urlparse(href).path.rstrip("/") or "/"
            except Exception:
                continue
            target = path_to_url.get(path)
            if target and target != page.url and path not in seen:
                seen.add(path)
                counts[target] += 1

    return counts


def _compute_signals(page: CrawledPage, incoming_links: int = 0) -> PageSignals:
    word_count = len(page.content.split())

    # --- information_density ---
    if word_count > 500:
        information_density = 1.0
    elif word_count > 200:
        information_density = 0.7
    elif word_count > 100:
        information_density = 0.4
    else:
        information_density = 0.1

    # --- technical_depth ---
    # Reward balanced code+prose. Penalise pure code dumps (autogenerated
    # API references, SDK docs, schema dumps) — many blocks, little prose.
    code_block_count = page.content.count("```") // 2
    if code_block_count == 0:
        technical_depth = 0.2   # conceptual content — not penalised
    elif code_block_count >= 10 or (code_block_count > 3 and word_count < 300):
        technical_depth = 0.4   # code dump — no bonus
    else:
        technical_depth = 0.9   # balanced tutorial/guide content

    # --- navigational_noise ---
    link_density = page.content.count("](") / max(word_count, 1)
    if link_density > 0.1:
        navigational_noise = 0.9
    elif link_density > 0.05:
        navigational_noise = 0.4
    else:
        navigational_noise = 0.1

    # --- onboarding_value ---
    if _ONBOARDING_URL.search(page.url):
        onboarding_value = 0.9
    elif _ONBOARDING_TITLE.search(page.title or ""):
        onboarding_value = 0.6
    else:
        onboarding_value = 0.1

    return PageSignals(
        information_density=information_density,
        technical_depth=technical_depth,
        navigational_noise=navigational_noise,
        onboarding_value=onboarding_value,
        url_boost=compute_url_boost(page.url),
        template_similarity=_compute_template_similarity(page.content),
        internal_link_authority=incoming_links,
    )


def _signals_to_score(signals: PageSignals, page: CrawledPage) -> int:
    score = 0

    # information density: -3 to +2
    if signals.information_density >= 0.9:
        score += 2
    elif signals.information_density >= 0.6:
        score += 1
    elif signals.information_density <= 0.2:
        score -= 3

    # good meta description: +2
    if page.description and len(page.description) > 50:
        score += 2

    # technical depth: +2 for balanced code+prose; code dumps get no bonus
    if signals.technical_depth >= 0.7:
        score += 2

    # navigational noise: -2 for heavy nav/index pages
    if signals.navigational_noise >= 0.7:
        score -= 2

    # onboarding value: +1 for entry-point pages
    if signals.onboarding_value >= 0.7:
        score += 1

    # url boost: direct delta from path pattern matching
    score += signals.url_boost

    # template penalty: up to -5 for highly template-like pages
    score -= round(signals.template_similarity * 5)

    # internal link authority: capped at +5
    score += min(signals.internal_link_authority // 3, 5)

    return score


# ---------------------------------------------------------------------------
# Main scoring function
# ---------------------------------------------------------------------------

def score_page(
    page: CrawledPage,
    page_clf: PageClassification,
    base_url: str,
    incoming_links: int = 0,
) -> ScoredPage:
    page_type = page_clf.page_type
    signals   = _compute_signals(page, incoming_links)

    # Hero (homepage) always top score
    if page.url.rstrip("/") == base_url.rstrip("/"):
        return ScoredPage(page=page, page_type=page_type, score=15, signals=signals, included=True)

    depth_penalty = min(page.depth * 0.5, 3)
    score = _base_score(page_type) + _signals_to_score(signals, page) - depth_penalty

    return ScoredPage(page=page, page_type=page_type, score=score, signals=signals)


# ---------------------------------------------------------------------------
# Score all pages with fallback logic
# ---------------------------------------------------------------------------

def score_all(
    pages: list[CrawledPage],
    classification: dict[str, PageClassification],
    base_url: str,
) -> list[ScoredPage]:
    # Compute incoming link counts once across all pages
    link_counts = _compute_incoming_links(pages)

    def _run(threshold: int) -> list[ScoredPage]:
        results = []
        for page in pages:
            page_clf = classification.get(page.url)
            if page_clf is None:
                continue
            sp = score_page(page, page_clf, base_url, link_counts.get(page.url, 0))
            if sp.score < threshold and sp.score != 15:  # never drop homepage
                continue
            results.append(sp)
        return results

    scored = _run(DROP_THRESHOLD)

    # Relax threshold if too few pages survive
    if len(scored) < 5:
        scored = _run(RELAXED_DROP_THRESHOLD)

    # Mark included, sort by score
    for sp in scored:
        sp.included = sp.score >= DROP_THRESHOLD

    scored.sort(key=lambda x: x.score, reverse=True)
    return scored
